spring.application.name=backend


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Drool_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false
jwt.secret=U29tZVN1cGVyU2VjdXJlS2V5Rm9ySldUQXV0aEV4YW1wbGUxMjM0NTY3ODkw
jwt.expiration=86400000
